# 开发环境配置
spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudcare?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# 自定义配置
cloudcare:
  # JWT配置
  jwt:
    secret: cloudcare-jwt-secret-key-2023222656458484849846546489
    expiration: 60
    header: Authorization
    token-start-with: Bearer
  # 文件上传路径
  file:
    upload-path: D:/cloudcare/upload/
    allowed-types: .jpg,.jpeg,.png,.gif,.doc,.docx,.pdf,.xlsx,.xls
  # 安全配置
  security:
    ignore-urls:
      - /api/auth/login
      - /api/auth/captcha
      - /api/auth/register
      - /druid/**
      - /doc.html
      - /webjars/**
      - /swagger-resources/**
      - /v3/api-docs/**
